---
title: "covid-polls"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{covid-polls}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = FALSE}
try({
  data_url <- "https://github.com/alarm-redist/redist-data/raw/main/data/king_county.rds"
  data_path <- tempfile()
  download.file(data_url, data_path)
})

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = file.exists(data_path)
)
set.seed(5118)
```

```{r setup}
library(senseweight)
```

We begin by setting up the survey design objects.
```{r}
axios_unweighted <- svydesign(ids = ~1, data = axios_subset)
svymean(~vaccinated, axios_unweighted, na.rm = TRUE)

formula_rake = ~gender + age + race_4way + educ + income6way + region + metro 

#Estimate weights:
rake_demos <- calibrate(design = axios_unweighted,
                        formula = formula_rake,
                        population = population_targets,
                        calfun = "raking")

svymean(~vaccinated, rake_demos, na.rm = TRUE)
vacc_estimates_df = as.data.frame(svymean(~vaccinated, rake_demos, na.rm = TRUE))
vacc_estimates = vacc_estimates_df$mean[2]
names(vacc_estimates) = NULL

```

```{r}
weights_axios = weights(rake_demos)*nrow(axios_subset)
Y = ifelse(axios_subset$vaccinated == "Yes", 1, 0)
RV_est = robustness_value(estimate = vacc_estimates-0.7, sigma2 = var(Y), weights = weights_axios)
print(RV_est)
```


```{r}
#Generate summary table:
print(xtable::xtable(
  data.frame(point_estimate = vacc_estimates*100, 
                                se = vacc_estimates_df$SE[2]*100,
                                RV=RV_est, cor_est = abs(cor(weights_axios,Y)))),
  include.rownames=FALSE)
```